# SUMMARY:
#
# Build and push an image using Docker Buildkit.
#
# DESCRIPTION:
#
# This does not need privileged access, unlike Docker in Docker (DIND). It has three stages:
#
# * clone the Git repository
# * build the binary
# * build and push the image containing the binary
#
# USAGE:
#
# Publishing images requires an access token. For hub.docker.com you can create one at https://hub.docker.com/settings/security
# This needs to be mounted as `$DOCKER_CONFIG/config.json`. To do this, you'll need to create a secret as follows:
#
#    export DOCKER_USERNAME=******
#    export DOCKER_TOKEN=******
#    kubectl create secret generic docker-config --from-literal="config.json={\"auths\": {\"https://index.docker.io/v1/\": {\"auth\": \"$(echo -n $DOCKER_USERNAME:$DOCKER_TOKEN|base64)\"}}}"
#
# REFERENCES:
#
# * https://github.com/moby/buildkit#expose-buildkit-as-a-tcp-service
# * https://blog.alexellis.io/building-containers-without-docker/
# * https://hub.docker.com/r/moby/buildkit
#
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: buildkit-go-v1.0.0
spec:
  arguments:
    parameters:
      - name: image_git_clone
        value: alpine/git:v2.26.2
      - name: repo
      - name: branch
        value: main
      - name: workdir
        value: /work
      - name: path
        value: .
      - name: image_builder
      - name: image_push
  entrypoint: main
  # We use a volume claim template so that we can have a shared workspace.
  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 64Mi
  templates:
    - name: main
      dag:
        tasks:
          - name: clone
            template: clone
            arguments:
              parameters:
                - name: repo
                  value: "{{workflow.parameters.repo}}"
                - name: branch
                  value: "{{workflow.parameters.branch}}"
                - name: workdir
                  value: "{{workflow.parameters.workdir}}"
                - name: image_git_clone
                  value: "{{workflow.parameters.image_git_clone}}"
          - name: build
            template: build
            arguments:
              parameters:
                - name: path
                  value: "{{workflow.parameters.path}}"
                - name: workdir
                  value: "{{workflow.parameters.workdir}}"
                - name: image_builder
                  value: "{{workflow.parameters.image_builder}}"
            depends: "clone"
          - name: image
            template: image
            arguments:
              parameters:
                - name: path
                  value: "{{workflow.parameters.path}}"
                - name: workdir
                  value: "{{workflow.parameters.workdir}}"
                - name: image_push
                  value: "{{workflow.parameters.image_push}}"
            depends: "build"
    - name: clone
      inputs:
        parameters:
          - name: repo
          - name: branch
          - name: workdir
          - name: image_git_clone
      container:
        volumeMounts:
          - mountPath: "{{inputs.parameters.workdir}}"
            name: work
        image: "{{inputs.parameters.image_git_clone}}"
        workingDir: "{{inputs.parameters.workdir}}"
        args:
          - clone
          - --depth
          - "1"
          - --branch
          - "{{inputs.parameters.branch}}"
          - --single-branch
          - "{{inputs.parameters.repo}}"
          - .
    - name: build
      inputs:
        parameters:
          - name: path
          - name: workdir
          - name: image_builder
      container:
        image: "{{inputs.parameters.image_builder}}"
        volumeMounts:
          - mountPath: "{{inputs.parameters.workdir}}"
            name: work
        workingDir: "{{inputs.parameters.workdir}}/{{inputs.parameters.path}}"
        env:
          - name: GO111MODULE
            value: "on"
        command:
          - sh
        args:
          - -c
          - |
            if [ ! -f go.mod ]; then
              go mod init golang-helloworld
            fi
            go mod tidy
            go mod download
            go mod verify
            go build -v -o main .
    - name: image
      inputs:
        parameters:
          - name: path
          - name: workdir
          - name: image_push
      volumes:
        - name: docker-config
          secret:
            secretName: docker-config
      container:
        readinessProbe:
          exec:
            command: [ sh, -c, "buildctl debug workers" ]
        image: moby/buildkit:v0.9.3-rootless
        volumeMounts:
          - name: work
            mountPath: "{{inputs.parameters.workdir}}"
          - name: docker-config
            mountPath: /.docker
        workingDir: "{{inputs.parameters.workdir}}/{{inputs.parameters.path}}"
        env:
          - name: BUILDKITD_FLAGS
            value: --oci-worker-no-process-sandbox
          - name: DOCKER_CONFIG
            value: /.docker
        command:
          - buildctl-daemonless.sh
        args:
          - build
          - --frontend
          - dockerfile.v0
          - --local
          - context=.
          - --local
          - dockerfile=.
          - --output
          - "type=image,name=docker.io/{{inputs.parameters.image_push}},push=true"